version: '3.8'

services:
  app:
    build: . 
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/employee_db
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge